// Code generated by "stringer -type=ClientState"; DO NOT EDIT.

package clis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotAction-0]
	_ = x[Closed-1]
	_ = x[Active-2]
	_ = x[OpenSession-3]
}

const _ClientState_name = "NotActionClosedActiveOpenSession"

var _ClientState_index = [...]uint8{0, 9, 15, 21, 32}

func (i ClientState) String() string {
	if i < 0 || i >= ClientState(len(_ClientState_index)-1) {
		return "ClientState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientState_name[_ClientState_index[i]:_ClientState_index[i+1]]
}
